data:
	@cd trueblocks-wallets ; make excel ; cd -
#	@cd dao-01 ; make excel ; cd -
#	@cd person-01 ; make excel ; cd -
#	@cd person-02 ; make excel ; cd -
#	@cd person-03 ; make excel ; cd -
#	@cd gitcoin-alpha ; make excel ; cd -

rebuild:
	@cd trueblocks-wallets ; ./doAll.sh ; make data ; cd -
#	@cd dao-01 ; ./doAll.sh ; make data ; cd -
#	@cd person-01 ; ./doAll.sh ; make data ; cd -
#	@cd person-02 ; ./doAll.sh ; make data ; cd -
#	@cd person-03 ; ./doAll.sh ; make data ; cd -
#	@cd gitcoin-alpha ; ./doAll.sh ; make data ; cd -
