data:
	@cd dao-01 ; make data ; cd -
	@cd gitcoin-alpha ; make data ; cd -
	@cd person-01 ; make data ; cd -
	@cd person-02 ; make data ; cd -
	@cd person-03 ; make data ; cd -
	@cd trueblocks-wallets ; make data ; cd -
