data:
	@cd trueblocks-wallets ; make data ; cd -
#	@cd dao-01 ; make data ; cd -
#	@cd person-01 ; make data ; cd -
#	@cd person-02 ; make data ; cd -
#	@cd person-03 ; make data ; cd -
#	@cd gitcoin-alpha ; make data ; cd -

rebuild:
	@cd trueblocks-wallets ; ./doAll.sh ; make data ; cd -
	@cd dao-01 ; ./doAll.sh ; make data ; cd -
	@cd person-01 ; ./doAll.sh ; make data ; cd -
	@cd person-02 ; ./doAll.sh ; make data ; cd -
	@cd person-03 ; ./doAll.sh ; make data ; cd -
#	@cd gitcoin-alpha ; ./doAll.sh ; make data ; cd -
